eureka:
    client:
        service-url:
            defaultZone: http://localhost:7001/eureka
management:
    endpoints:
        web:
            exposure:
                include: bus-refresh
rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
server:
    port: 3344
spring:
    application:
        name: cloud-config-center
    cloud:
        config:
            label: master
            server:
                git:
                    search-paths: '[springcloud-config]'
                    uri: https://github.com/activezjy/springcloud-config.git
